# Generated by Django 5.2 on 2025-05-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='ia_paid',
            new_name='is_paid',
        ),
    ]
